import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { MetricChip } from "@/components/ui/metric-chip";
import { Button } from "@/components/ui/button";

export default async function ClientPressReleasesPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser();
  const { data: orders } = await supabase.from("press_release_orders").select("id, headline, website_url, status, total_amount, admin_note, created_at, press_release_order_items(product_name, unit_price)").eq("user_id", user!.id).order("created_at", { ascending: false });
  return <div><div className="mb-6 flex items-end justify-between"><div><h1 className="font-display text-2xl font-medium">Press releases</h1><p className="mt-1 text-sm text-muted">Track review, writing, and distribution progress.</p></div><Link href="/press-releases"><Button size="sm">New request</Button></Link></div><div className="space-y-4">{orders?.map((order) => <article key={order.id} className="rounded-chip border border-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-medium">{order.headline}</h2><a className="mt-1 block text-sm text-brand-violet underline" href={order.website_url} target="_blank">{order.website_url}</a></div><MetricChip label="Status" value={order.status.replaceAll("_", " ")} tone={order.status === "published" ? "verified" : "price"} /></div><div className="mt-4 flex flex-wrap gap-2">{(order.press_release_order_items as unknown as { product_name: string; unit_price: number }[] | null)?.map((item) => <MetricChip key={item.product_name} label="Package" value={item.product_name} />)}<MetricChip label="Total" value={`৳${Number(order.total_amount).toLocaleString()}`} tone="price" /></div>{order.admin_note && <p className="mt-4 rounded-chip bg-paper p-3 text-sm"><span className="font-medium">Update from our team: </span>{order.admin_note}</p>}<p className="mt-3 text-xs text-muted">Requested {new Date(order.created_at).toLocaleDateString()}</p></article>)}{!orders?.length && <div className="rounded-chip border border-line bg-white p-8 text-center"><p className="text-muted">You have not submitted a press release yet.</p><Link className="mt-3 inline-block text-sm underline" href="/press-releases">Create your first request</Link></div>}</div></div>;
}
